import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ActionIcon, Box, Container, Flex } from "@mantine/core";
import { IconLogin } from "@tabler/icons-react";
import { useSession } from "next-auth/react";

// eslint-disable-next-line @typescript-eslint/require-await
export async function getStaticProps() {
  return {
    props: {},
  };
}

const Home: NextPage = () => {
  const { status } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={(theme) => ({
          minHeight: "100vh",
          backgroundColor: theme.colors.gray[3],
        })}
      >
        <Container p="sm">
          <Flex justify="space-between">
            <Link href="/menus">
              <span className="">My</span>
              <span>QR</span>
              <span>Menu</span>
            </Link>

            {status === "loading" && null}
            {status === "unauthenticated" && (
              <ActionIcon component={Link} href="/auth/login">
                <IconLogin />
              </ActionIcon>
            )}
            {status === "authenticated" && (
              <Link href={"/menus"}>Mis Menus</Link>
            )}
          </Flex>
        </Container>

        <Container p="sm" h="100%">
          <Flex justify="center" h="100%" align="center">
            <h2 className="text-4xl font-semibold text-slate-100">
              Landing Page
            </h2>
          </Flex>
        </Container>
      </Box>
    </>
  );
};

export default Home;
